### ISSUE TITLE
First File in Module Issues

### ISSUE THREAD

**Issue by leopoldodonnell** [edvinasbartkus/grails-coffeescript-resources#10]
FIrst files in Modules have a few parsing problems.
1. Block Comments generate an error
2. The first line following a class declaration needs to be blank in some cases

Both generate the message _Problem in line 1_

Here's a example from _Config.groovy_

```
coffeescript.modules = {
badBlockComment {
    files "src/coffee/blockComment"   
}

    blockCommentsOK {
  files "src/coffee/thisPasses", "src/coffee/blockComment"
}
noBlankLine {
  files "src/coffee/noFirstBlankLine"
}
}
```

blockComment.coffee

```
###
  This is a block comment
###
  class blockCommented
```

thisPasses.coffee

```
class ThisPasses

  member: 'there is a blank line above me'

  bar: 'bar'
```

noFirstBlankLine.coffee

```
class NoFirstBlankLine
  foo: 'foo'

  bar: 'bar'
```

This used to work prior to moving from grails 2.0.0RC1 to 2.0.0 - I've suspected my own environment, but haven't been able to identify the problem.

A careful person can workaround these issues, but it would be nice if someone with familiarity with the code could figure this out if it proves to be a problem.

**Comment by leopoldodonnell** [comment]
splix pointed out that this happens to him as well, but uninstalling the plugin and referencing it directly from BuildConfig works around the problem just fine.

Good luck getting to the bottom of this.

**Comment by edvinasbartkus** [comment]
Plugin don't use own module management.
Coffeescript resources uses the resources plugin module management.
