### ISSUE TITLE
Issues with coffeescript-resources:0.3.1

### ISSUE THREAD

**Issue by erajasekar** [edvinasbartkus/grails-coffeescript-resources#13]
When I add .coffee files in my ApplicationResources.groovy like , 

```
core {
    dependsOn 'jquery,jquery-ui,coffee'
    resource url: 'js/render.js', disposition: 'head'
}

coffee {
  resource url: 'coffee/render.coffee'
}
```

I am getting error

plugins.DefaultGrailsPluginManager Error configuring dynamic methods for plugin [resources:1.1.6]: Cannot create resource /coffee/render.coffee, is not a supported type
java.lang.IllegalArgumentException: Cannot create resource /coffee/render.coffee, is not a supported type
    at org.grails.plugin.resource.ResourceModule.newResourceFromArgs(ResourceModule.groovy:107)

Am I missing any configuration or setup ..? If so can you good documentation on how to get it working ..?

I started using prev version 0.2, it works fine, but it doesn't automatically compile changes to .coffee file while app is running, I had to restart app every time.. is that expected behavior ..? If not can you provide some hints on how to troubleshoot it ..?

Thanks,

**Comment by edvinasbartkus** [comment]
Seems like a change in resources plugin. Will try to fix it.

**Comment by erajasekar** [comment]
Great, Thanks!

Rajasekar.

On Thu, Apr 19, 2012 at 10:03 AM, Edvinas <
reply@reply.github.com

**Comment by ghost** [comment]
I get the same issue.
Is there a demo or documentation somewhere ?
Thank you
-<M>-

**Comment by edvinasbartkus** [comment]
Documentation can be found in README file.
Simply add resource entry into your Resources.groovy file with .coffee extension and it should be compiled to coffeescript.

Sorry for the long delay. I wish I could work with Grails on daily basis.
I hope it works for everyone now.

P.S. Because the plugin now  uses 1.3.1 coffeescript compiler I have upgraded it to 1.3.2 version.
