### ISSUE TITLE
Docs inprovement

### ISSUE THREAD

**Issue by splix** [edvinasbartkus/grails-coffeescript-resources#14]
Currently It's really not clear from docs (and sources), where I should put my `.coffee` files. 

I tried `src/coffee`, `src/cs` and `web-app/cs` - nothing works. For first options i'm getting 'resource not found', for last i'm receiving source of my coffeescript. So, i'm doing something wrong, but can't understand what.

Could you please update docs with detailed instruction how to configure plugin and where to put source files? Thanks!

**Comment by edvinasbartkus** [comment]
Hope it works now :-)

**Comment by splix** [comment]
Thanks!
