### ISSUE TITLE
Packaged plugin 0.3.4 contains an invalid dependency

### ISSUE THREAD

**Issue by MGotink** [edvinasbartkus/grails-coffeescript-resources#25]
An error occurs when installing grails-coffeescript-resources version 0.3.4 from the grails plugins repository:

```
| Loading Grails 2.2.0
| Error WARNING: Specified dependency definition build(rest-client-builder:1.0.2) is invalid! Skipping..
```

The rest-client-builder dependency in dependencies.groovy is invalid as it should contain a colon before the rest-client-builder definition:

``` groovy
build(":release:2.0.4", "rest-client-builder:1.0.2") {
```

I was unable to reproduce the same output by cloning this repository and running package-plugin on it.

**Comment by edvinasbartkus** [comment]
Thanks for pointing out.
Tomorrow will release 0.3.5 with the fix.

**Comment by MGotink** [comment]
Thanks for the fast response, the new release is working fine.
