### ISSUE TITLE
Plugin destroys all other resources on startup

### ISSUE THREAD

**Issue by martindobias** [edvinasbartkus/grails-coffeescript-resources#28]
I have set a very simple scenario with one coffee file in cs directory. It does not matter what is the content of the file.

No matter of, when I start the application, no resources are loaded and page ends with very confusing error that jQuery plugin is missing its .js resources.

| Error 2013-02-24 18:34:00,468 [http-bio-8080-exec-5] ERROR [/...].[default]  - Servlet.service() for servlet [default] in context with path [/...] threw exception
Message: Error applying layout : main
    Line | Method
->> 1110 | runWorker in ...\project\grails-app\views\layouts\main.gsp

---

|    603 | run       in     ''
^    722 | run . . . in     ''
Caused by GroovyPagesException: Error processing GroovyPageView: Error executing tag <r:layoutResources>: Module [jquery] depends on resource [/plugins/jquery-1.8.3/js/jquery/jquery-1.8.3.min.js] but the file cannot be found

It is caused by a simple presence of my coffee resource because if I temporarily remove the resource from ApplicationResources.groovy while the app is running, jQuery and other plugins start to work.

I can later return my resource back (application still has to be running) and suddenly it works, my resource gets compiled to .js and is accessible.

It seems that during application startup something wrong is with the state of coffeescript-resources plugin, I have found this error:

| Error 2013-02-24 18:33:50,921 [localhost-startStop-1] ERROR plugins.DefaultGrailsPluginManager  - Error configuring dynamic methods for plugin [resources:1.1.6]: java.lang.AssertionError: CoffeeScriptJs resource not found. Expression: coffeeScriptJsResource.exists()
Message: java.lang.AssertionError: CoffeeScriptJs resource not found. Expression: coffeeScriptJsResource.exists()

That points out to the state where coffee-script-1.3.3.js is not on its expected location. The file is present, so it is the path that is expected different. Perhaps at that moment the classpath is not set yet.

It must be the initialization phase where something gets wrong as without any change to actual script files I can get the application to work just by modifying ApplicationResources.groovy file on the fly.

My knowledge of Grails and plugins is very limited, but I guess the first time coffee resources are tried to be compiled by this plugin, the application is at point where it shall compile all the resources for the first time and not all plugin related resources are yet available for operation (like coffee-script-1.3.3.js). An error in coffeescript-plugin then breaks this stage completely, it stops in the middle.

I have come to this conclusion by monitoring a run directory of tomcat: .grails\2.2.0\projects...\tomcat\work\Tomcat\localhost...\grails-resources
First time the directory is only half filled with data. When I remove my coffee resource from ApplicationResources.groovy and get it back the rest of the resources (jQuery, angular, ...) gets generated and finaly my resource is compiled too.

Please help, thanks.

**Comment by edvinasbartkus** [comment]
Thanks for the details about the problem.
I will look into the issue Monday morning!

## 

Edvinas

**Comment by martindobias** [comment]
Hi, any update on the issue?
