### ISSUE TITLE
resources plugin integration

### ISSUE THREAD

**Issue by robokaso** [edvinasbartkus/grails-coffeescript-resources#5]
Given the name I think the general expectation is this plugin would be integrated with the resources plugin but it's not the case. Hope this is the intended in the future releases.

**Comment by edvinasbartkus** [comment]
That's right. Therefor it's still only 0.2.
For now the major difference is that this plugin allows to group .coffee files into modules and compile them as single output file. This is very practical if you play with MVC JS framework like Backbone.js. It allows you to have every class of model, controller, view in separate files and to group them and result in one. CoffeeScript compile wraps classes with ().call() method which makes it difficult to reuse classes that are declared in different files.

For 0.3 version I will make it compatible with Grails 2.0 and it will integrate with javascript resources plugin.
